StudentManagement1/StudentManagement1/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagement1.Controllers
{
    public class CourseController : Controller
    {
        private MobileAttendanceSystemDBContext db = new MobileAttendanceSystemDBContext();

        //
        // GET: /Course/


        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Course_Id")
            {
                return View(db.Courses.Where(x => x.Course_Id.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "Name")
            {
                return View(db.Courses.Where(x => x.Course_Name.StartsWith(search) || search == null).ToList());
            }

            else
            {
                return View(db.Courses.Where(x => x.Degree.Degree_Name.StartsWith(search) || search == null).ToList());
            }
        }

        //
        // GET: /Course/Details/5

        //public ActionResult Details(string id = null)
        //{
        //    Course course = db.Courses.Find(id);
        //    if (course == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(course);
        //}

        //
        // GET: /Course/Create

        public ActionResult Create()
        {
            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name");
            ViewBag.Semester_Id = new SelectList(db.Semesters, "Semester_Id", "Semester_Name");
            return View();
        }

        //
        // POST: /Course/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Course course)
        {
            try
            {

            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", course.Degree_Id);
            ViewBag.Semester_Id = new SelectList(db.Semesters, "Semester_Id", "Semester_Name", course.Semester_Id);
            return View(course);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // GET: /Course/Edit/5

        public ActionResult Edit(string id = null)
        {
            try
            {

            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", course.Degree_Id);
            ViewBag.Semester_Id = new SelectList(db.Semesters, "Semester_Id", "Semester_Name", course.Semester_Id);
            return View(course);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Course/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Course course)
        {
            //try
            //{

                if (ModelState.IsValid)
                {
                    db.Entry(course).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", course.Degree_Id);
                ViewBag.Semester_Id = new SelectList(db.Semesters, "Semester_Id", "Semester_Name", course.Semester_Id);
                return View(course);
            
            //}
            //catch (Exception)
            //{

            //    return View("Error");
            //}
        }

        //
        // GET: /Course/Delete/5

        public ActionResult Delete(string id = null)
        {
            try
            {
             
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Course/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {

                //to delete course from TeacherCourse table

                //to determin teachers list that assigned with this course
                List <TeacherCourse> teacherCourses = db.TeacherCourses.Where(x => x.Course_Id == id).ToList();
                if (teacherCourses != null)
                {
                    foreach (var item in teacherCourses)
                    {
                        //get total credit hours of teachers who teches that course from TeacherCreditHours table
                        TeacherCreditHours teacherCreditHours = db.TeacherCreditHours.Where(x => x.Teacher_Id == item.Teacher_Id).SingleOrDefault();
                        int totalCreditHours = teacherCreditHours.CreditHours;

                        //to determin students assigned to each teacher from TeacherCourseStudents table
                        List<TeacherCourseStudent> studentToRemove = db.TeacherCourseStudents.Where(x => x.TeacherCourse_Id == item.TeacherCourse_Id).ToList();

                        // to remove students related to courses
                        if (studentToRemove != null)
                        {
                            foreach (var item2 in studentToRemove)
                            {
                                db.TeacherCourseStudents.Remove(item2);
                                db.SaveChanges();
                            }
                        }


                        //to minus Credit hourse from teacherCreditHours table
                        Course course = db.Courses.Where(x => x.Course_Id == id).SingleOrDefault();
                        totalCreditHours = totalCreditHours - course.Credit_Hours;

                        //update credit hours in teacherCreditHours table
                        var updateCreditHours = db.TeacherCreditHours.FirstOrDefault(ad => ad.Teacher_Id == item.Teacher_Id);
                        updateCreditHours.CreditHours = totalCreditHours;
                        db.SaveChanges();

                        //remove course from teacher course table
                        db.TeacherCourses.Remove(item);
                        db.SaveChanges(); 
                        
                    }
                }
                
      
                List<StudentCourse> studentCourse = db.StudentCourses.Where(x => x.Course_Id == id).ToList();
                foreach (var item in studentCourse)
                {
                    //to minus course credit hours from studentCredit Hours Table from StudentCourse table
                     List<StudentCreditHours> studentCreditHours = db.StudentCreditHours.Where(x => x.Student_Id == item.Student_Id).ToList();
                     
                    foreach (var item2 in studentCreditHours)
                     {
                         //get total enrolled credit hours 
                         int totalCreditHours = item2.CreditHours;
                         //get course credit hours to minus 
                         Course course = db.Courses.Where(x => x.Course_Id == id).SingleOrDefault();
                        // minus course credit hours from toal credit hours
                         totalCreditHours = totalCreditHours - course.Credit_Hours;


                         //update credit hours in teacherCreditHours table
                         var updateCreditHours = db.StudentCreditHours.FirstOrDefault(ad => ad.Student_Id == item.Student_Id);
                         updateCreditHours.CreditHours = totalCreditHours;
                         db.SaveChanges();


                         //to delete course from StudentCourse table
                         db.StudentCourses.Remove(item);
                         db.SaveChanges();
                     }
                }
            
            //to delete course from course table
            Course cours = db.Courses.Find(id);
            db.Courses.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

StudentManagement1/StudentManagement1/Controllers/DegreeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagement1.Controllers
{
    public class DegreeController : Controller
    {
        private MobileAttendanceSystemDBContext db = new MobileAttendanceSystemDBContext();

        //
        // GET: /Degree/

        public ActionResult Index()
        {
            return View(db.Degrees.ToList());
        }

       
        //
        // GET: /Degree/Create

        public ActionResult Create()
        {
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Dept_Name");
            return View();
        }

        //
        // POST: /Degree/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Degree degree)
        {
            try
            {
            if (ModelState.IsValid)
            {
                db.Degrees.Add(degree);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Dept_Name",degree.Dept_Id);
            return View(degree);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // GET: /Degree/Edit/5

        public ActionResult Edit(string id = null)
        {
            try
            {
            Degree degree = db.Degrees.Find(id);
            if (degree == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dept_Id = new SelectList(db.Departments, "Dept_Id", "Dept_Name", degree.Dept_Id);
            return View(degree);
         
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Degree/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Degree degree)
        {
            try
            {
            if (ModelState.IsValid)
            {
                db.Entry(degree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Department_Id = new SelectList(db.Departments, "Dept_Id", "Dept_Name", degree.Dept_Id);
            return View(degree);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // GET: /Degree/Delete/5

        public ActionResult Delete(string id = null)
        {
            try
            {

                Degree degree = db.Degrees.Find(id);
            if (degree == null)
            {
                return HttpNotFound();
            }
            return View(degree);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Degree/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
            Degree degree = db.Degrees.Find(id);
            db.Degrees.Remove(degree);
            db.SaveChanges();
            return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

StudentManagement1/StudentManagement1/Controllers/SemesterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManagement1.Controllers
{
    public class SemesterController : Controller
    {
        private MobileAttendanceSystemDBContext db = new MobileAttendanceSystemDBContext();

        //
        // GET: /Semester/

        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Degree_Name")
            {
                return View(db.Semesters.Where(x => x.Degree.Degree_Name.StartsWith(search) || search == null).ToList());
            }
            else 
            {
                return View(db.Semesters.Where(x => x.Semester_Name.StartsWith(search) || search == null).ToList());
            }

        }

        ////
        //// GET: /Semester/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    try
        //    {
        //    Semester semester = db.Semesters.Find(id);
        //    if (semester == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(semester);
        //    }
        //    catch (Exception)
        //    {

        //        return View("Error");
        //    }
        //}

        //
        // GET: /Semester/Create

        public ActionResult Create()
        {
            try
            {

            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name");
            return View();

            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Semester/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Semester semester)
        {
            try
            {

            if (ModelState.IsValid)
            {
                db.Semesters.Add(semester);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", semester.Degree_Id);
            return View(semester);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // GET: /Semester/Edit/5

        public ActionResult Edit(int id = 0)
        {
            try
            {
            Semester semester = db.Semesters.Find(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", semester.Degree_Id);
            return View(semester);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Semester/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Semester semester)
        {
            try
            {

            if (ModelState.IsValid)
            {
                db.Entry(semester).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Degree_Id = new SelectList(db.Degrees, "Degree_Id", "Degree_Name", semester.Degree_Id);
            return View(semester);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // GET: /Semester/Delete/5

        public ActionResult Delete(int id = 0)
        {
            try
            {
            Semester semester = db.Semesters.Find(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }

        //
        // POST: /Semester/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
            Semester semester = db.Semesters.Find(id);
            db.Semesters.Remove(semester);
            db.SaveChanges();
            return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View("Error");
            }
        }



        public ActionResult SemesterCourses(int id, string degreeid)
        {
            List<Course> semestercourses = db.Courses.Where(x => x.Semester_Id == id && x.Degree_Id == degreeid).ToList();

            return View(semestercourses);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

StudentManagement1/StudentManagement1/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Please check the URL.</h1>
<h1> The page you are looking for cannot be found</h1>

StudentManagement1/StudentManagement1/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
     <title>@ViewBag.Title - Mobile Attendance System</title>
     <meta name="keywords" content="" />
     <meta name="description" content="" />
  <link href="~/Content/themes/templatemo_style.css" rel="stylesheet" type="text/css" media="screen" />
<script  lang="javascript" type="text/javascript">
    function clearText(field) {
        if (field.defaultValue == field.value) field.value = '';
        else if (field.value == '') field.value = field.defaultValue;
    }
</script>
</head>
<body>

<div id="templatemo_header">
            
    <div id="site_title">
        
        <a >Mobile Attendance System </a>
        
    </div> <!-- end of site_title -->
    
   <div id="header_right">
  
    
   </div>
    
    <div class="cleaner"></div>
    
</div> <!-- end of header -->

<div id="templatemo_menu_wrapper">
	
    <div id="templatemo_menu">
        <ul>
            <li><a href="@Url.Action("Index", "Department")" ><span></span>Departments</a></li>
            <li><a href="@Url.Action("Index", "Teacher")"><span></span>Teachers</a></li>
            <li><a href="@Url.Action("Index", "Degree")" ><span></span>Degrees</a></li>
            <li><a href="@Url.Action("Index", "Semester")"><span></span>Semesters</a></li>
            <li><a href="@Url.Action("Index", "Student")"><span></span>Students</a></li>
            <li><a href="@Url.Action("Index", "Course")"><span></span>Courses</a></li>
        </ul>    	
	</div>
</div> <!-- end of templatemo_menu -->


<div id="templatemo_main"> <span class="tm_bottom"></span>
	
<div id="templatemo_content">
    
    	<div class="entry">
                 @RenderSection("featured", required: false)
                 @RenderBody()

            	</div>
  	    <br /> <br />  <br /> <br /> <br /> <br />  <br /> <br />
        @*<div class="post_box pb_last">
            <div class="header">
                <h2><a href="#">Cum sociis natoque penatibus et magnis</a></h2>
              <div class="tag"><strong>Tags:</strong> <a href="#">Photography</a>, <a href="#">Free Photos</a>, <a href="#">HDR</a></div>
                <span class="posted_date">
                    @DateTime.Today.Month/@DateTime.Now.Day                    
                    <strong> @DateTime.Now.Year</strong>
                </span>
            </div>
            <img src="/Images/templatemo_image_01.jpg" alt="image" />
            <div class="pb_right">
                <p>Praesent mattis varius quam. Vestibulum ullamcorper ipsum nec augue. Vestibulum auctor odio eget ante. Nunc commodo, magna pharetra semper vehicula, dui ligula feugiat elit, et euismod nunc orci ut libero. Etiam sodales massa vel metus. Mauris et elit quis mauris aliquet luctus.</p>
                <div class="comment"><a href="#">64 comments</a></div>
		  </div>
            <div class="cleaner"></div>
    </div>*@
        
        
     

    </div>
    
    <div id="templatemo_sidebar">
    	<div class="sidebar_box">
        	<h3>Profile</h3>
            <div class="sb_content">
                <ul class="sidebar_menu">
            	<li><a href="@Url.Action("Logout", "AdminLogin")">Logout</a></li>
                <li><a href="@Url.Action("ChangePassword", "AdminLogin")">Change Password</a></li>
                </ul>
            </div>
        </div>
        
        <div class="sidebar_box">
        	<h3>Session Time</h3>
            <div class="sb_content">
            	<ul class="sidebar_menu">
                    
                    <li><a href ="@Url.Action("Index", "SessionTime")">Session Time</a></li>

                </ul>
            </div>
        </div>
        
       @* <div class="sidebar_box">
        	<h3>Archives</h3>*@
            @*<div class="sb_content">
            	<ul class="sidebar_menu">
                    <li><a href="#">CSS Templates</a></li>
                    <li><a href="#">Web Design Ideas</a></li>
                    <li><a href="#">Free Wallpapers</a></li>
                    <li><a href="#">Free Pixel Fonts</a></li>
                    <li><a href="#">Illustrator Tutorials</a></li>
                    <li><a href="#">3D Character Tutorials</a></li>
                </ul>
            </div>*@
       @* </div>*@
        
        <div class="sidebar_box">
        	@*<h3>Our Friends</h3>
            <div class="sb_content">
            	<ul class="sidebar_menu">
                    <li><a href="#" target="_parent">Free Flash Files</a></li>
                    <li><a href="#" target="_parent">Free CSS Templates</a></li>
                    <li><a href="#" target="_blank">Web Design Tips</a></li>
                    <li><a href="#" target="_blank">Flash XML Galleries</a></li>
                    <li><a href="#" target="_blank">Inspiring Flash Websites</a></li>
                </ul>
            </div>*@
        </div>
    </div>
    
    <div class="cleaner"></div>
</div> <!-- end of main -->

<div id="templatmeo_bottom">
	<div class="bottom_box">
    	<h5><span>Sed Necest</span> Suspendisse a nibh</h5>
        <p>Duis vitae velit sed dui malesuada dignissim. Donec mollis aliquet ligula. Maecenas adipiscing elementum ipsum.</p>
		<a href="#" class="continue">more info</a>
    </div>
    
    <div class="bottom_box">
    	<h5><span>Lorem ipsum</span> dolor sit amet</h5>
        <p>Vestibulum eleifend, enim ut molestie pulvinar, purus est fringilla augue, ut tristique nunc neque a libero.</p>
		<a href="#" class="continue">more info</a>
    </div>
    
    <div class="bottom_box">
    	<h5><span>Recent</span> Blog Post</h5>
       	<ul class="bottom_box_list">
        	<li><a href="#">Duis vitae velit sed lesuada dignissim.</a></li>
            <li><a href="#">Donec mollis aliquet ligula.</a></li>
            <li><a href="#">Maecenas adipiscing elementum ipsum.</a></li>
        </ul>
    </div>

</div> <!-- end of bottom -->

<div id="templatemo_footer">

	<ul class="footer_menu">
        <li class="first"><a href="#">Home</a></li>
        <li><a href="@Url.Action("Index", "Department")" >Departments</a></li>
        <li><a href="@Url.Action("Index", "Teacher")">Teachers</a></li>
        <li><a href="@Url.Action("Index", "Degree")" >Degrees</a></li>
        <li><a href="@Url.Action("Index", "Semester")">Semesters</a></li>
        <li><a href="@Url.Action("Index", "Student")">Students</a></li>
        <li><a href="@Url.Action("Index", "Course")">Courses</a></li>
	</ul>
    
	Copyright © 2012 <a href="#">NTU</a>
@*<a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a></div>*@

 @Scripts.Render("~/bundles/jquery")
        @* @RenderSection("scripts", required: false) *@
        @if (IsSectionDefined("scripts"))
        {
            @RenderSection("scripts")
        }
</body>
</html>

StudentManagement1/StudentManagement1/Views/Shared/_TeacherLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
     <title>@ViewBag.Title - Mobile Attendance System</title>
     <meta name="keywords" content="" />
     <meta name="description" content="" />
  <link href="~/Content/themes/templatemo_style.css" rel="stylesheet" type="text/css" media="screen" />
<script  lang="javascript" type="text/javascript">
    function clearText(field) {
        if (field.defaultValue == field.value) field.value = '';
        else if (field.value == '') field.value = field.defaultValue;
    }
</script>
</head>
<body>

<div id="templatemo_header">
            
    <div id="site_title">
        
        <a >Mobile Attendance System </a>
        
    </div> <!-- end of site_title -->
    
   <div id="header_right">
  
    
   </div>
    
    <div class="cleaner"></div>
    
</div> <!-- end of header -->

<div id="templatemo_menu_wrapper">
	
    <div id="templatemo_menu">
        <ul>
            <li><a href="@Url.Action("Courses", "Attendance",new { id = User.Identity.Name })" ><span></span>Attendance</a></li>
            <li><a href="@Url.Action("CourseSessions", "Attendance", new { id = User.Identity.Name })"><span></span>Sessions</a></li>
        </ul>    	
	</div>
</div> <!-- end of templatemo_menu -->


<div id="templatemo_main"> <span class="tm_bottom"></span>
	
<div id="templatemo_content">
    
    	<div class="entry">
                 @RenderSection("featured", required: false)
                 @RenderBody()

            	</div>
  	    <br /> <br />  <br /> <br /> <br /> <br />  <br /> <br />
        @*<div class="post_box pb_last">
            <div class="header">
                <h2><a href="#">Cum sociis natoque penatibus et magnis</a></h2>
              <div class="tag"><strong>Tags:</strong> <a href="#">Photography</a>, <a href="#">Free Photos</a>, <a href="#">HDR</a></div>
                <span class="posted_date">
                    @DateTime.Today.Month/@DateTime.Now.Day                    
                    <strong> @DateTime.Now.Year</strong>
                </span>
            </div>
            <img src="/Images/templatemo_image_01.jpg" alt="image" />
            <div class="pb_right">
                <p>Praesent mattis varius quam. Vestibulum ullamcorper ipsum nec augue. Vestibulum auctor odio eget ante. Nunc commodo, magna pharetra semper vehicula, dui ligula feugiat elit, et euismod nunc orci ut libero. Etiam sodales massa vel metus. Mauris et elit quis mauris aliquet luctus.</p>
                <div class="comment"><a href="#">64 comments</a></div>
		  </div>
            <div class="cleaner"></div>
    </div>*@
        
        
     

    </div>
    
    <div id="templatemo_sidebar">
    	<div class="sidebar_box">
        	<h3>@User.Identity.Name</h3>
            <div class="sb_content">
                <ul class="sidebar_menu">
            	<li><a href="@Url.Action("Logout", "Attendance")">Logout</a></li>
                <li><a href="@Url.Action("ChangePassword", "Attendance")">Change Password</a></li>
                </ul>
            </div>
        </div>
        
  
    </div>
    
    <div class="cleaner"></div>
</div> <!-- end of main -->

<div id="templatmeo_bottom">
	<div class="bottom_box">
    	<h5><span>Sed Necest</span> Suspendisse a nibh</h5>
        <p>Duis vitae velit sed dui malesuada dignissim. Donec mollis aliquet ligula. Maecenas adipiscing elementum ipsum.</p>
		<a href="#" class="continue">more info</a>
    </div>
    
    <div class="bottom_box">
    	<h5><span>Lorem ipsum</span> dolor sit amet</h5>
        <p>Vestibulum eleifend, enim ut molestie pulvinar, purus est fringilla augue, ut tristique nunc neque a libero.</p>
		<a href="#" class="continue">more info</a>
    </div>
    
    <div class="bottom_box">
    	<h5><span>Recent</span> Blog Post</h5>
       	<ul class="bottom_box_list">
        	<li><a href="#">Duis vitae velit sed lesuada dignissim.</a></li>
            <li><a href="#">Donec mollis aliquet ligula.</a></li>
            <li><a href="#">Maecenas adipiscing elementum ipsum.</a></li>
        </ul>
    </div>

</div> <!-- end of bottom -->

<div id="templatemo_footer">

	<ul class="footer_menu">
        <li class="first"><a href="#">Home</a></li>
        <li><a href="@Url.Action("Index", "Department")" >Departments</a></li>
        <li><a href="@Url.Action("Index", "Teacher")">Teachers</a></li>
        <li><a href="@Url.Action("Index", "Degree")" >Degrees</a></li>
        <li><a href="@Url.Action("Index", "Semester")">Semesters</a></li>
        <li><a href="@Url.Action("Index", "Student")">Students</a></li>
        <li><a href="@Url.Action("Index", "Course")">Courses</a></li>
	</ul>
    
	Copyright © 2012 <a href="#">NTU</a>
@*<a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a></div>*@

 @Scripts.Render("~/bundles/jquery")
        @* @RenderSection("scripts", required: false) *@
        @if (IsSectionDefined("scripts"))
        {
            @RenderSection("scripts")
        }
</body>
</html>